# Perfect 2 node network, no noise from either computation on the nodes or communication between nodes
stacks:
  - name: Node1
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null
  - name: Node2
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null
  - name: Node3
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null
  - name: Node4
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null


hubs:
  - name: Hub1
    connections:
      - stack: Node1
        distance: 10
      - stack: Node2
        distance: 12
      - stack: Node3
        distance: 3
      - stack: Node4
        distance: 15

    link_typ: perfect
    link_cfg:
      dummy: null

    clink_typ: default
    clink_cfg:
      distance: 0
      speed_of_light: 1

    schedule_typ: todo
    schedule_cfg:
      dummy: null
