stacks:
  - name: Alice
    qdevice_typ: abstract
    qdevice_cfg:
      num_positions: 3
  - name: Bob
    qdevice_typ: abstract
    qdevice_cfg:
      num_positions: 3

links:
  - stack1: Alice
    stack2: Bob
    typ: perfect
    cfg:
      state_delay: 2000

clinks:
  - stack1: Alice
    stack2: Bob
    typ: default
    cfg:
      delay: 400