stacks:
  - name: alice
    qdevice_typ: generic
    qdevice_cfg: 
      dummy: null
  - name: bob
    qdevice_typ: generic
    qdevice_cfg: 
      dummy: null

links:
  - stack1: alice
    stack2: bob
    typ: perfect
    cfg:
      state_delay: 1000

clinks:
  - stack1: alice
    stack2: bob
    typ: default
    cfg:
      delay: 0.5